name: list_to_csv_excel
description: "This flutter package to create a csv and excel file for your data in flutter applications and web apps."
version: 1.0.0
homepage:

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  file_saver: ^0.2.14
  intl: ^0.20.2
  path: ^1.9.0
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
